import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Embeds the markdown documentation into a TypeScript module so the resources
 * work under both `tsx` (development) and the bundled `dist/local.js`, without
 * a runtime file read or an esbuild text loader.
 */
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const docsDir = join(root, "src", "resources", "docs");
const outFile = join(root, "src", "resources", "docs.generated.ts");

const docs = {
  architectureMd: "architecture.md",
  migrationMd: "migration.md",
};

let output =
  "// AUTO-GENERATED by scripts/generate-docs.mjs from src/resources/docs/*.md — do not edit.\n\n";

for (const [name, file] of Object.entries(docs)) {
  const text = readFileSync(join(docsDir, file), "utf8");
  output += `export const ${name} = ${JSON.stringify(text)};\n\n`;
}

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, output);
console.log(`Generated ${outFile}`);
